if coredump is to big, delete it instead of archiving
arangodb/oskar pull request #442
Opened 2022-10-13 12:25 UTC by dothebart

2022-10-13 12:53 UTC, dothebart commented
https://jenkins01.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/1330/ including other changes.

2022-10-14 08:35 UTC, dothebart commented on jenkins/helper/test_launch_controller.py
> +    MAX_TOTAL_CORESIZE_MB=int(os.environ['MAX_TOTAL_CORESIZE'])
I think yes, we need this. You want to archive no more than `n` corefiles, up to `m` bytes individual size, `o` bytes combined size.
even if `n` goes down to a size way below `o` in result.

2022-10-14 08:58 UTC, dothebart commented on jenkins/helper/test_launch_controller.py
> +            for one_crash_file in files_unsorted:
we have two loops here:
- if single files are to big or combined size is to big the loop you marked.
- below a loop if the remaining count is to high
But yes, should indicate why its been deleted.

2022-10-17 11:05 UTC, KVS85 commented on jenkins/helper/test_launch_controller.py
> +    MAX_TOTAL_CORESIZE_MB=int(os.environ['MAX_TOTAL_CORESIZE'])
Yes. That's why we don't need it as a separate variable. Max total size is either calculated or ignored (if option regarding number of cores was off).

2022-10-17 11:06 UTC, KVS85 commented on jenkins/helper/test_launch_controller.py
> +            for one_crash_file in files_unsorted:
It's not implemented in the way I described. Current implementation is non-optimal and doesn't take options to turn off either number of cores or individual core size or both.

2022-10-19 09:45 UTC, dothebart commented on jenkins/helper/test_launch_controller.py
> +            for one_crash_file in files_unsorted:
the msising disabling of the count condition was added:
```
        total_files_too_big = 0 < MAX_TOTAL_CORESIZE_MB < size_count
                if 0 < MAX_COREFILE_SIZE_MB < size:
                if 0 < MAX_TOTAL_CORESIZE_MB < size_count:
        if len(files_unsorted) > core_max_count > 0:
```
work down to putting `-1` to any of these conditions to disable them, hence the comparisons to `0` to implement this.
Tripple-compares seem to be a bit odd on first sight, but pylint wanted it to be done like that.

2022-10-19 09:47 UTC, dothebart commented
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/24997/

2022-10-21 09:54 UTC, dothebart commented
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/25061/ run green except for real test failures.

2022-10-21 16:23 UTC, naushniki approved these changes

2022-10-24 16:01 UTC, KVS85 requested changes
`MAX_TOTAL_CORESIZE_MB` should be removed, global loop over sorted (asc) by sizes coredumps should be used with `core_max_count` condition check and `MAX_COREFILE_SIZE_MB` break.

2022-10-24 16:04 UTC, KVS85 commented on jenkins/helper/test_launch_controller.py
> +            for one_crash_file in files_unsorted:
`len(files_unsorted) > core_max_count > 0`

These lines are hard to interpret. Please use conjunction of expressions.

2022-10-28 11:11 UTC, dothebart commented
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/25242/

2022-11-03 14:30 UTC, KVS85 approved these changes

2022-11-03 14:32 UTC, merged