invoke machine cleaner
arangodb/oskar pull request #449
Opened 2022-10-26 17:16 UTC by dothebart

2022-10-26 17:28 UTC, KVS85 requested changes

2022-10-26 17:28 UTC, KVS85 commented on helper.psm1
> +    python.exe jenkins/helper/clear_machine.py
Should use `IS_JENKINS` check.

2022-11-17 17:20 UTC, KVS85 commented on helper.psm1
> +    python.exe jenkins/helper/clear_machine.py
https://github.com/arangodb/oskar/blob/master/jenkins/helper/prepareOskar.ps1

2022-11-22 19:16 UTC, KVS85 approved these changes

2022-11-22 19:17 UTC, KVS85 commented
https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-matrix/4083/

2022-11-23 08:42 UTC, fceller approved these changes

2022-11-23 11:27 UTC, KVS85 commented
https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-matrix/4088/

2022-11-23 12:18 UTC, merged