only run coverage if tests are successfull
arangodb/oskar pull request #479
Opened 2022-12-21 10:59 UTC by dothebart

2022-12-22 22:06 UTC, naushniki approved these changes
@dothebart Good job!

2023-01-19 16:12 UTC, KVS85 requested changes

2023-01-25 08:47 UTC, goedderz commented on jenkins/runCoverageRocksDB.fish
> +  echo $status
Debugging leftover?
```suggestion
```

2023-01-25 08:59 UTC, dothebart commented on jenkins/runCoverageRocksDB.fish
> +echo "exiting $exitcode"
I would like to leave this one, so one has a clear indicator.

2023-01-25 08:59 UTC, dothebart commented on jenkins/runCoverageRocksDB.fish
> +  end
changed accordingly.

2023-01-26 10:20 UTC, dothebart commented
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/27300/ devel run
https://jenkins01.arangodb.biz/job/arangodb-devel-coverage/494/ coverage

2023-01-26 17:11 UTC, dothebart commented
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/27320/
https://jenkins01.arangodb.biz/job/arangodb-devel-coverage/496/

2023-01-27 15:27 UTC, dothebart commented
https://jenkins01.arangodb.biz/job/arangodb-3.10-coverage/53/
https://jenkins01.arangodb.biz/job/arangodb-3.9-coverage/140/
https://jenkins01.arangodb.biz/job/arangodb-3.8-coverage/190/

2023-01-27 19:38 UTC, KVS85 approved these changes

2023-01-27 19:38 UTC, merged