Feature/mt coverage merge
arangodb/oskar pull request #491
Opened 2023-02-13 18:50 UTC by dothebart

2023-03-03 16:51 UTC, KVS85 requested changes

2023-03-03 16:51 UTC, KVS85 commented on scripts/coverage.fish
> +and mkdir /work/combined
```suggestion
and rm -rf ./combined; and mkdir ./combined
```

2023-03-03 16:51 UTC, KVS85 commented on scripts/coverage.fish
> +and python3 "$WORKSPACE/jenkins/helper/aggregate_coverage.py" /work/gcov /work/combined/result
Check whether WORKSPACE is empty:
- yes: use `$WORKDIR/jenkins/helper/aggregate_coverage.py`
- no: use `$WORKSPACE/jenkins/helper/aggregate_coverage.py`

Use `$INNERWORKDIR/gcov $INNERWORKDIR/combined/result`.

2023-03-08 20:44 UTC, KVS85 commented
- [ ] https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/28110/
- [ ] https://jenkins01.arangodb.biz/job/arangodb-ANY-coverage/46/

2023-03-08 20:44 UTC, KVS85 approved these changes

2023-03-09 16:09 UTC, KVS85 commented
- [ ] https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/28129/
- [ ] https://jenkins01.arangodb.biz/job/arangodb-ANY-coverage/48/

2023-03-09 18:32 UTC, alexbakharew approved these changes
LGTM. But we need to get rid of redundant output.

2023-03-09 18:32 UTC, alexbakharew commented on jenkins/helper/aggregate_coverage.py
> +        self.job = jobs
Please use `self.jobs` as we have array of jobs

2023-03-09 18:32 UTC, alexbakharew commented on jenkins/helper/aggregate_coverage.py
> +        print('------')
Do we need here this output here?

2023-03-09 18:32 UTC, alexbakharew commented on jenkins/helper/aggregate_coverage.py
> +        print(self.params)
And here?

2023-03-09 18:55 UTC, KVS85 commented
- [ ] https://jenkins01.arangodb.biz/job/arangodb-ANY-coverage/49/

2023-03-09 21:11 UTC, naushniki approved these changes

2023-03-10 11:49 UTC, KVS85 commented
- [ ] https://jenkins01.arangodb.biz/job/arangodb-ANY-coverage/50/

2023-03-10 12:06 UTC, alexbakharew reviewed
Additional comments

2023-03-10 12:06 UTC, alexbakharew commented on jenkins/helper/aggregate_coverage.py
> +            print('.')
Is this output required?

2023-03-10 12:25 UTC, dothebart commented on jenkins/helper/aggregate_coverage.py
> +        sub_jobs = next_jobs
if you have an odd number of directories, one remains for the next layer of the tree.

2023-03-10 12:29 UTC, dothebart commented
I will clean up the output and the variable names in the next iteration.

2023-03-10 16:47 UTC, merged