The Linux release executables of ArangoDB require a <= 4K page size
arangodb/oskar pull request #512
Opened 2023-04-21 11:37 UTC by Simran-B

See https://github.com/arangodb/docs/pull/1345

2023-04-21 13:34 UTC, dothebart requested changes
please add hints to `getconf PAGESIZE`.

2023-04-21 13:46 UTC, Simran-B commented
The download pages are not an appropriate place for system administration advice. They merely list the requirements. Added it to the docs: https://github.com/arangodb/docs/pull/1345

2023-04-21 15:53 UTC, dothebart commented
please make it a link then.

2023-05-12 14:56 UTC, jsteemann reviewed
LGTM in general, but snippets for 3.11 seem to be missing by now.

2024-06-13 09:01 UTC, Simran-B commented
Submitted a request to the marketing team to make the necessary changes on the new Wordpress site: https://arangodb.slack.com/archives/C9PPCJ4HF/p1718267406644329

2024-06-13 09:01 UTC, closed without merging