make sure the python really did its job
arangodb/oskar pull request #519
Opened 2023-05-31 15:27 UTC by dothebart

2023-05-31 15:33 UTC, KVS85 requested changes

2023-05-31 15:33 UTC, KVS85 commented on scripts/runFullTests.fish
> +    echo "python exited $status"
`$status` isn't persisted.

2023-05-31 15:33 UTC, KVS85 commented on scripts/runFullTests.fish
> +    echo "python exited $status"
`$status` isn't persisted.

2023-05-31 15:33 UTC, KVS85 commented on scripts/runFullTests.fish
> +    echo "python exited $status"
`$status` isn't persisted.

2023-05-31 15:33 UTC, KVS85 commented on scripts/runFullTests.fish
> +    echo "python exited $status"
`$status` isn't persisted.

2023-06-01 16:51 UTC, dothebart commented
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/30238/ launched with [b83deca](https://github.com/arangodb/oskar/pull/519/commits/b83decae4618cfc23c77170a993a99232a949706)
https://jenkins01.arangodb.biz/job/arangodb-matrix-pr-mac-onlycatch.x86-64/25290/ launched with [4ea277c](https://github.com/arangodb/oskar/pull/519/commits/4ea277cd734cb9ec4f3b9d4183ca0116504ac506) to revalidate the forgotten condition.

2023-06-01 16:54 UTC, naushniki approved these changes
LGTM

2023-06-01 16:55 UTC, KVS85 approved these changes

2023-06-01 16:55 UTC, merged