remove compile option `-fno-stack-protector`
arangodb/oskar pull request #529
Opened 2023-07-24 21:43 UTC by jsteemann

2023-07-26 18:11 UTC, MBkkt requested changes
I don't think it's good idea.
Just why? Yes, it should be same by default, but for what reason we need to do something implicit instead of explicit

2023-07-27 09:06 UTC, jsteemann commented
> I don't think it's good idea. Just why? Yes, it should be same by default, but for what reason we need to do something implicit instead of explicit

This PR _removes_ an explicitly set compile option, so we use _less_ custom options and more rely on the defaults.
IMO this has the following advantages:
- potentialler safer executables (compiled-in stack protection
- going with the compiler defaults (more tested/used compiler options rather than less tested/used ones)
- more uniform builds (there are different ways to build ArangoDB, and currently only some set this option - so we currently have different builds depending on how they are built!)
- small complexity reduction in build infrastructure (Oskar + CMake)

2023-07-27 09:26 UTC, MBkkt commented
> potentialler safer executables

Well and potentially slower, our perf tests don't really prove that it is not slower.

> going with the compiler defaults (more tested/used compiler options rather than less tested/used ones)

Already done, if it's not default it's strange compiler.

> more uniform builds

I don't agree, for different compilers, os etc it could be different defaults, so we implicit could have different in terms of options binaries


> small complexity reduction in build infrastructure (Oskar + CMake)

You probably meant circleci.
I think we can fix it another way.
We can just put it in all non maintainer release builds in our cmake instead of oskar/circleci

2023-07-27 09:47 UTC, jsteemann commented
> Well and potentially slower, our perf tests don't really prove that it is not slower.

Yes, the potential slowdown is of course a disadvantage. That's why I ran the performance tests.

> Already done, if it's not default it's strange compiler.

Why is there a performance difference then when removing the option from our build scripts?
 
> I don't agree, for different compilers, os etc it could be different defaults, so we implicit could have different in terms of options binaries

Agree, but that is true for all other options which we don't set explicitly.

> You probably meant oskar + circleci. I think we can fix it another way. We can just put it in all non maintainer release builds in our cmake instead of oskar/circleci

I agree this option, if we want to set it explicitly, should be set by our CMake and not by anything outside.

2023-07-27 09:54 UTC, MBkkt commented
>  That's why I ran the performance tests.

I already wrote, and you ignored it.
"our perf tests don't really prove that it is not slower."

> Why is there a performance difference then when removing the option from our build scripts?

For strange/new compiler it could be.
Someone could decide safer by default builds is better and change default.

>Agree, but that is true for all other options which we don't set explicitly.

In ideal world all options are explicit. But we couldn't do it, so I suggest to do not make more implicit options

2024-05-28 11:49 UTC, closed without merging